include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    annotate_overrides: true
    always_declare_return_types: true
    avoid_double_and_int_checks: true
    avoid_print: false
    cast_nullable_to_non_nullable: true
    avoid_dynamic_calls: false
    type_annotate_public_apis: false
    always_use_package_imports: true
    avoid_relative_lib_imports: true
