name: websocket_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  lottie: ^1.2.2
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  web_socket_channel: ^2.1.0
  stomp_dart_client: ^0.4.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true