name: websocket_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  dart_code_metrics: ^4.13.0
  rxdart: ^0.27.3
  provider: ^6.0.2
  flutter_bloc: ^8.0.1

  http: ^0.13.4
  dio: ^4.0.4
  web_socket_channel: ^2.1.0
  stomp_dart_client: ^0.4.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.13

  lottie: ^1.2.2
  animated_button: ^0.2.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  pinput: ^2.2.7
  dropdown_button2: ^1.4.0
  flutter_svg: ^1.0.3
  sliding_switch: ^1.0.0
  flutter_neumorphic: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cards/