name: websocket_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  web_socket_channel: ^2.1.0
  stomp_dart_client: ^0.4.3
  device_info_plus: ^3.2.2
  platform_device_id: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true